
if [ ! -d "/REDE" ]; then
  mkdir /REDE
fi

mkdir /REDE/ALAN-SOARES
mkdir /REDE/ANDREA-SANTOS
mkdir /REDE/BRUNO-OLIVEIRA
mkdir /REDE/CAMILA-LIRA
mkdir /REDE/CARLOS-SOUSA
mkdir /REDE/CAROLINE-NASCIMENTO
mkdir /REDE/DANIEL-SANTANA
mkdir /REDE/DARIO-FARIAS
mkdir /REDE/EDUARDO-RIOS
mkdir /REDE/FABIO-SILVA
mkdir /REDE/FELIPE-MACHADO
mkdir /REDE/FELIPE-BARRIOS
mkdir /REDE/FLÁVIO-SOUZA
mkdir /REDE/FRANCISCO-CAVALCANTE
mkdir /REDE/GABRIEL-CREPALDI
mkdir /REDE/GABRIEL-LIMA
mkdir /REDE/GABRIEL-RODRIGUES
mkdir /REDE/GABRIELY-SILVA
mkdir /REDE/GUILHERME-ALVES
mkdir /REDE/GUSTAVO-TAVARES
mkdir /REDE/HENRIQUE-CABRAL
mkdir /REDE/ISAAC-SOUZA
mkdir /REDE/ISABELLY-MESQUITA
mkdir /REDE/JOÃO-SOARES
mkdir /REDE/JONATHAN-FREITAS
mkdir /REDE/KAUÃ-MOTA
mkdir /REDE/LUCAS-SANTOS
mkdir /REDE/LUCAS-ANDRADE
mkdir /REDE/MATHEUS-CARVALHO
mkdir /REDE/NATALIA-MOREIRA
mkdir /REDE/NICOLAS-NASCIMENTO
mkdir /REDE/PALLOMA-SANTOS
mkdir /REDE/RAISSA-CARMO
mkdir /REDE/RAPHAELA-MELO
mkdir /REDE/REBECCA-GUEDES
mkdir /REDE/RIAM-ANDRE
mkdir /REDE/ROGERIO-JUNIOR
mkdir /REDE/SABRINA-BENEVIDES
mkdir /REDE/WALDANIA-OLIVEIRA

ls /REDE

echo "Pastas criadas com sucesso."
